### ISSUE TITLE
Custom create/update call

### ISSUE THREAD

**Issue by DAN-DanielPiotrowski** [KasualBusiness/prestashop-api#72]
**Prestashop version:** 1.8

**Node version:** 18.17

**Describe the bug**
Problem with custom call when i try to create a record it returns strange error to provide parameter that has already been provided. I tried both ways.

First attemp:
const createotp = await prestashopAPI
      .custom<{ item: Item }>("otptoken")
      .create<{ id_customer: number }>({
        id_customer: id,
});
error: 
{
  errors: [ { code: 41, message: 'parameter "id_customer" required' } ]
}

Second attemp:
const createotp = await prestashopAPI
      .custom<{ item: Item }>("otptoken")
      .create<{ id_customer: number }>(
        {
          id_customer: id,
        },
        { json: true }
      );
error: errors: 
[
    {
      code: 127,
      message: 'XML error : String could not be parsed as XML\n' +
        'XML length : 17\n' +
        'Original XML : {"id_customer":2}'
    }
  ]

**Expected behavior**
Well, I expect to create a record. Update function has the same issue (
{
  errors: [ { code: 90, message: 'id is required when modifying a resource' } ] - even if Id is provided
}
), all of others methods work such as get, list, delete

**Comment by yourikopecky** [comment]
Hello,

Thanks for filling this issue.

I don't know how the endpoint is handling the data since it's a custom endpoint but in your first example, are you sure that id_customer shouldn't be passed as a query parameter?

For the second example, the error is saying that it's expecting XML instead of json which is normal since you're passing json: true.

**Comment by DAN-DanielPiotrowski** [comment]
I don't understand what you mean by typing "query parameter", I was doing this according to your docs and i didn't see there any other way to provide data. Maybe I overlook something but i don't think so. That's the custom call example:
```await custom<{ item: Item }>("my-custom-route").create<{ name: string }>({ name: "My name" });```
and about endpoint its nothing special, here I provide code that works with prestashop default webservice but i can't manage to make it work with your library:
![otp](https://github.com/KasualBusiness/prestashop-api/assets/98353519/f3dace61-c702-4f30-8093-9e3be9fe40bc)

**Comment by yourikopecky** [comment]
Thanks for providing another example. I think I know why you're having an error.

You have to wrap `id_customer: id`  in `otp` like this:
```
await prestashopAPI
.custom<{ item: Item }>("otptoken")
.create<{ id_customer: number }>({
  otp: {
    id_customer: id
  }
);
```

Wrapping `customer_id` in `otp` will generate an xml like this:
```
<?xml version="1.0"?>
<prestashop>
  <otp>
    <customer_id>1</customer_id>
  </otp>
</prestashop>
```

The code that you provided earlier in the first example generate this xml:
```
<?xml version="1.0"?>
<prestashop>
  <customer_id>1</customer_id>
</prestashop>
```

Let me know if that worked.

**Comment by DAN-DanielPiotrowski** [comment]
Now it works, such a simple answer - so silly that i didn't not even think that it can work that way haha
Thanks for help!
